FROM ezbot-dev-pre-rosdep:latest

RUN git clone https://github.com/VincidaB/ezBotV2.git /ezBotV2-git
# COPY . /ezBotV2-git
WORKDIR /ezBotV2-git

RUN apt-get update && \
		apt-get upgrade -y && \
		rosdep update && rosdep install --from-paths src --ignore-src -r -y