on:
  push:
    branches:
      - main

jobs:
  build_and_test_ros2:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest
    steps:
      - name: Build and run tests
        uses: ros-tooling/action-ros-ci@0.4.4
        with:
          package-name: my_package
          target-ros2-distro: jazzy